net-im/py-zapzap: Update to 6.4.0
- Update list of build dependencies
- Add a post-patch target to fix the program version that does not match
  the distribution version. This discrepancy causes the following error:

===>   Generating temporary packing list
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.11/site-packages/installer/__main__.py", line 98, in <module>
    _main(sys.argv[1:], "python -m installer")
  File "/usr/local/lib/python3.11/site-packages/installer/__main__.py", line 86, in _main
    with WheelFile.open(args.wheel) as source:
  File "/usr/local/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/installer/sources.py", line 162, in open
    with zipfile.ZipFile(path) as f:
         ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/zipfile.py", line 1311, in __init__
    self.fp = io.open(file, filemode)
              ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/poudriere/ports/default/net-im/py-zapzap/work-py311/zapzap-6.4.0/dist/zapzap-6.4.0*.whl'
*** Error code 1

ChangeLog:	https://github.com/rafatosta/zapzap/releases/tag/6.4.0
Reported by:	Rafael Tosta <notifications@github.com>

ChangeLog:	https://github.com/rafatosta/zapzap/releases/tag/6.4.0
Reported by:	Rafael Tosta <notifications@github.com>