emulators/ripes: unbundle devel/cereal to fix the armv7 build
The bundled version of cereal is outdated and produces this build error:

In file included from /wrkdirs/usr/ports/emulators/ripes/work/Ripes-2.2.6/external/VSRTL/graphics/vsrtl_componentgraphic.cpp:14:
In file included from /wrkdirs/usr/ports/emulators/ripes/work/Ripes-2.2.6/external/VSRTL/external/cereal/include/cereal/archives/json.hpp:56:
/wrkdirs/usr/ports/emulators/ripes/work/Ripes-2.2.6/external/VSRTL/external/cereal/include/cereal/external/rapidjson/document.h:319:82: error: cannot assign to non-static data member 'length' with const-qualified type 'const SizeType' (aka 'const unsigned int')
  319 |     GenericStringRef& operator=(const GenericStringRef& rhs) { s = rhs.s; length = rhs.length; }
      |                                                                           ~~~~~~ ^
/wrkdirs/usr/ports/emulators/ripes/work/Ripes-2.2.6/external/VSRTL/external/cereal/include/cereal/external/rapidjson/document.h:325:20: note: non-static data member 'length' declared const here
  325 |     const SizeType length; //!< length of the string (excluding the trailing NULL terminator)
      |     ~~~~~~~~~~~~~~~^~~~~~
1 error generated.

Unbundle devel/cereal to get an up to date version which does not
exhibit this issue and to follow our policy on unbundling.

Approved by:	portmgr (build fix blanket)
MFH:		2026Q2