misc/py-numcodecs: Fix BUILD_DEPENDS
- Add missing py-numpy1
- Remove lang/cython: it is done by USE_PYTHON=cython

The error message is as follows:
===>  Configuring for py311-numcodecs-0.16.5
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 385, in <module>
    run_setup(with_extensions)
  File "setup.py", line 366, in run_setup
    + vlen_extension()
      ^^^^^^^^^^^^^^^^
  File "setup.py", line 208, in vlen_extension
    import numpy
ModuleNotFoundError: No module named 'numpy'
...
*** Error code 1

Stop.
make: stopped making "configure" in /usr/ports/misc/py-numcodecs

Approved by:	portmgr (blanket)
Reference:	https://pkg-status.freebsd.org/beefy23/data/150amd64-default/14bd0e320b77/logs/py311-numcodecs-0.16.5.log
		https://pkg-status.freebsd.org/beefy16/data/135amd64-default/14bd0e320b77/logs/py311-numcodecs-0.16.5.log